# docker-compose.yml

version: "3.9"
services:
  fastapi:
    build: .
    command: uvicorn fastapi_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    command: streamlit run streamlit_dashboard/app.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - .:/app